version = 0.1

[default]
[default.global.parameters]
stack_name = "salesforce-agent"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "salesforce-agent"
region = "us-east-1"
image_repositories = []
disable_rollback = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

# Development environment
[dev]
[dev.deploy.parameters]
parameter_overrides = [
    "Environment=development",
    "LogLevel=debug"
]

# Staging environment
[staging]
[staging.deploy.parameters]
parameter_overrides = [
    "Environment=staging",
    "LogLevel=info"
]

# Production environment
[prod]
[prod.deploy.parameters]
parameter_overrides = [
    "Environment=production",
    "LogLevel=warn"
]
confirm_changeset = true
capabilities = "CAPABILITY_IAM"